import streamlit as st
from equity_research import get_financials,score_company,data_pull,prepare_prompt

st.set_page_config(
    page_title="Equity Research Platform",
    page_icon="📈",
    layout="wide"
)
st.title("Equity Analysis")
ticker=st.text_input("Enter the Ticker: ")
presses_or_not=st.button("Analyze")

if presses_or_not:
    if ticker:
        with st.spinner("Fetching Data and Generating report..."):
            data=get_financials(ticker)
            data_given=data_pull(data)
            recommendation=score_company(data)
            report=prepare_prompt(ticker)
        
        tab1,tab2=st.tabs(["Score and Metrics","AI generated Report"])

        with tab1:
            st.subheader(f"Analysis for : {ticker.upper()}")

            # 3 Levels of Verdict
            verdict=recommendation["Verdict"]
            if verdict=="Buy":
                st.success(f"Verdict is {verdict}")
            elif verdict=="Hold":
                st.warning(f"Verdict is {verdict}")
            elif verdict=="Buy":
                st.error(f"Verdict is {verdict}")
            
            #Display of Metrics
            col1, col2, col3 = st.columns(3)
            with col1:
                st.metric("Market Cap", f"${data_given['Market Cap']:,.0f}")
                st.metric("P/E Ratio", f"{data_given['P/E Ratio']:.2f}")
                st.metric("EPS", f"${data_given['EPS']:.2f}")
            with col2:
                st.metric("Gross Margin", f"{data_given['gross_margin']:.1f}%")
                st.metric("Net Margin", f"{data_given['net_margin']:.1f}%")
                st.metric("Revenue Growth", f"{data_given['rev_growth']:.1f}%")
            with col3:
                st.metric("ROE", f"{data_given['ROE']:.1f}%")
                st.metric("D/E Ratio", f"{data_given['Debt/Equity']:.2f}")
                st.metric("EV/EBITDA", f"{data_given['EV']/data_given['EBITDA']:.1f}x")
            
            st.subheader("Scores for each Metric: ")
            scores=recommendation["Scores"]
            st.dataframe(scores)
        
        with tab2:
            st.subheader("Report Generated by Groq AI: ")
            st.markdown(report)



    else:
        st.warning("Please Enter a Ticker")